apiVersion: v1
kind: Service
metadata:
  name: business-platform
  labels:
    app: business-platform
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: business-platform
